### PR TITLE
Add options for em, startup and video editing in teams page

### PR DESCRIPTION
**Pull request by Avy2808**
image
image

Added domains which were previously undefined in teams page for 2023 - 2024.

### CODE REVIEW

**Comment by Avy2808** [comment]
@lawanyabaghel

**Comment by Avy2808** [comment]
@lawanyabaghel Ma'am please review.
#40

**Comment by lawanyabaghel** [comment]
Name of domain is Startup Founder. So write the full name instead of startup

**Comment by lawanyabaghel** [comment]
> image image
> 
> Added domains which were previously undefined in teams page for 2023 - 2024.

Name of domain is Startup Founder. So write the full name instead of startup

**Comment by Avy2808** [comment]
@lawanyabaghel Done Ma'am.

**Pull request merged**
