### PR TITLE
class -> className for jsx attributes, horizontal scroll correction 

### LINKED ISSUE #19: Change `class` tag to `className`
This change requires changing the `class` tag in the JSX with `className`

### PR DESCRIPTION
**Pull request by Shubhambawner**
Resolves #19

### CODE REVIEW

**Comment by Shubhambawner** [comment]
@sahil9001 @AyushAgrawal25 @Nikhil-Chacko

**Review by Shubhambawner — COMMENTED** [review]
Resolves #20

**Comment by AyushAgrawal25** [comment]
@sahil9001 review it once and merge the PR.

**Comment by sahil9001** [comment]
LGTM👍

**Comment by sahil9001** [comment]
What I think is this is pretty big PR to review, would be better if you could split it to different parts. @AyushAgrawal25 any suggestions?

**Comment by AyushAgrawal25** [comment]
> What I think is this is pretty big PR to review, would be better if you could split it to different parts. @AyushAgrawal25 any suggestions?

We can not a problem. But you don't really need to check each and every line, just write a regexp or simple Shift+Ctrl+F will work for this purpose.

**Comment by sahil9001** [comment]
Yeah, I know that as well but you can't verify if everything works. Well the change looks fine but some attributes doesn't work properly with `class`  -> `className` change, so was unsure about it. Because to revert a change this big will affect other parts as well so that would impact upcoming PRs

**Comment by AyushAgrawal25** [comment]
> Yeah, I know that as well but you can't verify if everything works. Well the change looks fine but some attributes doesn't work properly with `class` -> `className` change, so was unsure about it. Because to revert a change this big will affect other parts as well so that would impact upcoming PRs

I am not sure this happens, never seen one, but I trust you. I am keeping it a low priority, I kind of need to finish a few tests before this.

**Comment by Shubhambawner** [comment]
Sure, we can hold this back, but as far as I have tested, there is no issue in my local
also, unfortunately there are 2 comits to this pr, className one and issue #20 , as b4 this I had only 2 branches and from both there were active PRs, so this got stacked.

**Comment by sahil9001** [comment]
Ideally 1 PR should resolve 1 issue, because it's easier to check and merge. Also if someone wants to revert then that'll revert that issue only, so makes sense to resolve 1 issue per PR. Closing this as it has multiple issues resolved. You can make another PR for different issue.

**Pull request closed without merging**
